name: Build and Deploy Code

on: [push,pull_request]

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    -  name: pulling git repo
       uses: action/checkout@v2
    -  name: fast learning
       run: echo "hi all"
   